---
- name: Install login banner
  hosts: workshop-w1
  gather_facts: no
  vars:
    banner:
    - key: legalnoticecaption
      val: Hello Summit!
    - key: legalnoticetext
      val: Ansible and Windows rocks!
  tasks:
    - name: Set registry
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: "{{ item.key }}"
        data: "{{ item.val }}"
        type: multistring
      with_items: "{{ banner }}"
