---
- name: Provision Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - manage-instances
  vars:
    teardown: false
  tasks:
  - include_role:
      name: "manage-{{ instance_loc }}-instances"
